---
name: Base

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    # at 03:33 on Friday
    - cron: "33 3 * * 5"

concurrency:
  group: ${{ forgejo.workflow }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: base-amd64
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: "false"

      - name: Setup mise-en-place
        uses: https://github.com/jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          github_token: "${{ secrets.GH_TOKEN }}"

      - name: Get date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >>$FORGEJO_OUTPUT

      - name: Setup cache container
        uses: https://data.forgejo.org/actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          # yamllint disable-line rule:line-length
          key: "container-${{ hashFiles('./Dockerfile') }}-${{ steps.date.outputs.date }}"
          # restore only the same hash
          restore-keys: |
            container-${{ hashFiles('./Dockerfile') }}-
            container-
          path: "/var/tmp/buildah-cache-*/*"

      - name: Setup QEMU
        run: |
          mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
          podman run --privileged --rm docker.io/tonistiigi/binfmt --install all

      - name: Login to Docker Hub
        uses: https://github.com/docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: "docker.io"
          username: "${{ secrets.DOCKER_USER }}"
          password: "${{ secrets.DOCKER_TOKEN }}"

      - name: Build (push)
        run: |
          mise run build:ci --push
          mise run build --push
